services:
  - name: esp32-audio-server
    type: web
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install protobuf>=5.26.1
      pip install -r requirements.txt
    startCommand: "gunicorn -b 0.0.0.0:10000 app:app"
    plan: free
    autoDeploy: true
